/**
 * Converts a text to a JS Doc comment.
 * @param text the text that should be converted.
 */
export const toJSDocComment = (name: string, comment?: string): string => {
  const comments = comment ? `* ${comment.trim().replace('\n+$', '').replace(/\n/g, '\n  * ')}` : ``;
  return `/**${comments}
 * ${name}
 * @autogenerated
 */\n`;
};
